name: Cypress Tests

on:
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config-file: [cypress.CI.config.js, cypress.CI_mob.config.js]
    env:
      CI: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Cypress binary
        run: npx cypress install

      - name: Run Cypress tests
        run: npx cypress run --config-file ${{ matrix.config-file }} --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
